django_2ndex/proTwo/appTwo/urls.py
from django.urls import path
from . import views


app_name = 'appTwo'
urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),

]

django_2ndex/proTwo/proTwo/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('appTwo.urls')),
]

django_2ndex/proTwo/appTwo/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django import forms
from django.urls import reverse

# Create your views here.

class NewTaskForm(forms.Form):
  task = forms.CharField(label='New Task')

def index(request):
  if 'tasks' not in request.session:
    request.session['tasks'] = []
  return render(request,"appTwo/index.html", {
    'tasks': request.session['tasks']
  })

def add(request):
  if request.method == 'POST':
    form = NewTaskForm(request.POST)
    if form.is_valid():
      task = form.cleaned_data['task']
      request.session['tasks'] += [task]
      return HttpResponseRedirect(reverse('appTwo:index'))
    else:
      return render(request, 'appTwo/add.html', {
        'form': form
      })
  return render(request, 'appTwo/add.html',{
    'form':NewTaskForm()
  })

django_2ndex/proTwo/appTwo/templates/appTwo/add.html
{% extends "appTwo/layout.html" %}
{% load static %}
 

{% block body %}
<h6>coming from add.html</h6>
<form action="{% url 'appTwo:add' %}"method='POST'>
  {% csrf_token %}
  <h1>Add Task</h1>
  {{ form }}
  <input type="submit">
</form>
<a href="{% url 'appTwo:index' %}">Index page</a
>
{% endblock %}

django_2ndex/proTwo/appTwo/templates/appTwo/index.html
{% extends "appTwo/layout.html" %}
{% load static %}
 

{% block body %}
<h2>coming from index.html</h2>
{% for task in tasks %}
  <li>{{ task }}</li>
  {% endfor %}
  <a href="{% url 'appTwo:add' %}">Add Task</a>
{% endblock %}

django_2ndex/proTwo/appTwo/templates/appTwo/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% load static %}
  <link rel="stylesheet" href="{% static 'appTwo/styles.css' %}">
  <title>appTwo</title>
</head>
<body>
  {% block body %}
  
  {% endblock %}
  
</body>
</html>