djangotest_firstex/proj3/app3/urls.py
from django.urls import include
from django.urls import path
from . import views


app_name = 'app3'
urlpatterns = [
    path('', views.index, name='index'), 
    path('add/', views.add, name='add'),

]

djangotest_firstex/proj3/proj3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app3/', include('app3.urls')),
]

djangotest_firstex/proj3/app3/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse

class NewTaskForm(forms.Form):
  task = forms.CharField(label='New Task')
  # priority = forms.IntegerField(label='Priority', max=10)


# reason to delete tasks in here is to make session
# it will be under index function
# tasks = [ 'foo' ]

# to create table in django
# python manage.py migrate



def index(request):
  if 'tasks' not in request.session:
    request.session['tasks'] = []
  return render(request, 'app3/index.html', {
    'tasks' : request.session['tasks']
  })

def add(request):
  if request.method == 'POST':
    form = NewTaskForm(request.POST)
    if form.is_valid():
      task = form.cleaned_data['task']
      request.session['tasks'] += [task]
      return HttpResponseRedirect(reverse('app3:index'))
    else:
      return render(request,'app3/add.html',{
        'form':form
      })
  return render(request, 'app3/add.html', {
    "form":NewTaskForm()
  })

djangotest_firstex/proj3/app3/templates/app3/add.html
{% extends 'app3/layout.html' %}
{% load static %}

{% block body %}

<form action="{% url 'app3:add' %}" method="post">
  {% csrf_token %}
  <h1>Add Task</h1>
  {{ form }}
  <input type='submit'>
</form>
<a href="{% url 'app3:index' %}">Back To Index</a>

{% endblock %}

djangotest_firstex/proj3/app3/templates/app3/index.html
{% extends 'app3/layout.html' %}
{% load static %}


  {% block body %}
  {% for task in tasks %}
  <li>{{ task }}</li>
  {% endfor %}
  <a href="{% url 'app3:add' %}">Add Task</a>
  {% endblock %}
  

djangotest_firstex/proj3/app3/templates/app3/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>This is layout Title</title>
</head>
<body>
  {% block body %}

  
  {% endblock %}
  
</body>
</html>